spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nydb?useUnicode=true&serverTimezone=Asia/Seoul&useSSL=false
    username: nayeonglee
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8900
